### PR TITLE
*:lock::high_heel::bug: Fixed SSL :lock: invalid chain configuration …

### LINKED ISSUE #77: Install SSL cert from CA
### :stop_button: :tired_face: 

~~I'm creating this issue because the PositiveSSL people have still not [refunded my money](https://github.com/ibgib/ibgib/issues/74#issuecomment-256502152) (or offered a different cert option) and I need to continue development. It has only been about 16 hours, but I still confess myself a bit disappointed. Ah well.~~ :slightly_frowning_face:

~~So, I'm not sure how to tell whether a certificate will be accepted on mobile devices or not. I don't have the :dollar:s to just throw at this, so I'll have to wait until I get my money back and figure something else out.~~

Fatigue => slightly whiny :baby_bottle: 

### Solving  SSL :lock: 

Fortunately, the PositiveSSL help desk did NOT whine and DID do their job (:clap: :clap:) and pointed me to reevaluate my nginx configuration. Being a DevOps newb, I didn't realize that an SSL misconfiguration could lead some browsers to show green (SSL :lock:) with other browsers showing red :lock:, as I only naively thought that it would be due to not having the root CA on the device.

So, after spending all of yesterday afternoon and evening attempting and failing to configure nginx, I decided to call it quits and try again today. Woke up this morning at 4:00 AM thinking about how to approach troubleshooting the problem, and I came up with a couple (seemingly obvious) ideas:

* Stop running the containers with the `-d` flag to actually get logging feedback from nginx.
  * `docker-compose up -d` => `docker-compose up`
* Ensure that my cert/key are correct and matching in both nginx and web server.
  * The certs live on both containers, as placing certs on the nginx redirect server was part of the fix for a broken certificate chain. (still not sure why it was green on desktop and some mobile device browsers)

So, the feedback from the logging was essential in seeing that right off, one of the problems was that it was not copying the cert and key to the nginx server. This was causing the nginx server to continually fail and restart. After correcting this, I got a different error (!) of 502 Bad Gateway.

At this point I visually compared the cert/key on both machines, and they were indeed the same. Still no dice on the gateway.

The logging was indicating that the upstream server was not being found. This, plus a couple other troubleshooting steps, and I became pretty sure it was hinging on the correct way to connect to the upstream. I found a very similar SO question to my scenario [here](http://stackoverflow.com/questions/39202964/how-to-reach-another-container-from-a-dockerised-nginx), the main difference being it was port 80 => 8080 and I needed a variation that used SSL.

Eventually, it led me to this `default.conf` addition:
```
# (same 80 config not shown)

server {
    listen        443;
    server_name www.ibgib.com;
    ssl on;
    ssl_certificate /etc/nginx/ssl/www_ibgib_com/www_ibgib_com.crt;
    ssl_certificate_key /etc/nginx/ssl/www_ibgib_com/www_ibgib_com.key;
    ssl_prefer_server_ciphers on;

    location / {
      # web is the service name in docker-compose.yml
      proxy_pass      https://web:16816;
    }
}

server {
    listen        443;
    server_name ibgib.com;
    ssl on;
    ssl_certificate /etc/nginx/ssl/www_ibgib_com/www_ibgib_com.crt;
    ssl_certificate_key /etc/nginx/ssl/www_ibgib_com/www_ibgib_com.key;
    ssl_prefer_server_ciphers on;
    return 301 https://www.$host$request_uri;
}
```
This, combined with adding separate networks in `docker-compose.yml` and a `depends_on` clause in the `nginx-redirect` fixed all of my issues.

I failed to mention that I also changed my `nginx-redirect` config from `image` to `build`. Here is the updated section in `docker-compose.yml`:

```
  nginx-redirect:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
     - web
    restart: always
    networks:
      - front
```

### Success! :fireworks: 

So, this renewed attack with these changes ended up giving me a green SSL :lock: in the mobile devices. It also gave me an A+ rating at [SSL Analyzer](https://www.ssllabs.com/ssltest/analyze.html?d=www.ibgib.com), where before I received a B from a broken chain. 

I also have the naked + explicit `https` redirecting properly, so my redirect server is now fully implemented.

Thanks PositiveSSL!

### PR DESCRIPTION
**Pull request by bill-mybiz**
…(nginx)

* See #77 for details.

attr: meta

issue: closes #77

### CODE REVIEW

**Comment by rob3c** [comment]
It looks like there's an inconsistency with 301s and `$host$request_uri` sometimes is missing `www`.

**Comment by bill-mybiz** [comment]
@rob3c Hmm, I was just now bringing it down and redeploying to fix a bug in the ident email login link. Are you able to hit all variations of the redirects now? (My testing shows that everything is now properly getting redirected to `https://www.ibgib.com`)

**Comment by bill-mybiz** [comment]
e.g. 
www.ibgib.com
ibgib.com
https://ibgib.com

all get redirected to 
https://www.ibgib.com

**Comment by rob3c** [comment]
I was just reading the commit changes, and mentioned the inconsistency I saw. I haven't actually tried the permutations to see what really happens :-)

**Comment by rob3c** [comment]
I understand my mistake now. The url already has `www`, so it isn't required in the redirect! Glad you're configuring it and not me lol

**Comment by bill-mybiz** [comment]
Haha :laughing: 

I was starting to think "Oh no..." because I saw what you mean. Yeah, I _think_ my reasoning was that the `$host` would already have `www` in it. Whatever the case is, I don't want to touch it again right now! haha :sweat_smile: lol

**Pull request merged**
